In [1]:
import numpy as np 
a = np.arange(6)
print(a)


[0 1 2 3 4 5]


In [4]:
py_list=[1,2,3,4,5,6,7,8,9]
np_array= np.array([1,2,3,4,5,6,7,8,9])
print(type(py_list))
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [17]:
np_array= np.array([1,2,3,4,5,6,7,8,9])
py_multi=[[1,2,3],[4,5,6],[7,8,9]] 
mp_multi=np_array.reshape(3,3)#3 satir 3 sutunluk 2 boyutlu bir matris olusturur
print(mp_multi)
print(py_multi)
print(np_array.ndim)#boyutunu gösterir
print(mp_multi.ndim)

print(np_array.shape)#kaça kaçlık oldugunu gösterir mesela 9 eleman(sütun) var 1 satir (9,1) 
print(mp_multi.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
1
2
(9,)
(3, 3)
