In [4]:
import numpy as np
result = np.array([1,3,5,7,9])
print(result)

[1 3 5 7 9]


In [13]:
result = np.arange(1,10)#1 den 10 a kadar sayilari yazdir
print(result)

[1 2 3 4 5 6 7 8 9]


In [12]:
result = np.arange(10,100,3)#10 dan 100 a kadar sayilari 3 er arttirarak yazdir
print(result)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]


In [7]:
result = np.zeros([10])#10 tane 0 olusturur
print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
result = np.ones([10])#10 tane 1 olusturur
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
result = np.linspace(0,100,5)#başlangıç ve bitiş değerini 5 e boler ve sayilari ona göre yazdirir
print(result)

[  0.  25.  50.  75. 100.]


In [15]:
result = np.linspace(0,5,5)
print(result)

[0.   1.25 2.5  3.75 5.  ]


In [18]:
result =np.random.randint(0,10)#0 ile 10 arasında random bir sayi olustur
print(result)

3


In [23]:
result =np.random.randint(20)#0 ile 10 arasında random bir sayi olustur
print(result)

14


In [26]:
result =np.random.randint(1,10,3)#1 ile 10 arasında random 3 tane sayi olustur
print(result)

[4 8 1]


In [28]:
result =np.random.rand(5)#0 ile 1 arasında 5 tane sayi üretir
print(result)

[0.26917656 0.18062057 0.83068592 0.22378142 0.82824411]


In [31]:
result =np.random.randn(5)#-1 ile 1 arasında 5 tane sayi üretir
print(result)

[-0.4683967   0.61431188  0.66522259 -0.71807419  0.66889101]


In [37]:
np_array =np.arange(50)#0 dan 50 ye kadar sayi üretir
np_multi=np_array.reshape(5,10)
print(np_multi.sum(axis=1))#satirlarin toplamini verir
print(np_multi.sum(axis=0))#sutunlarin toplamini verir
print(np_multi)

[ 45 145 245 345 445]
[100 105 110 115 120 125 130 135 140 145]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [44]:
rnd_numbers =np.random.randint(1,100,10)#1 ile 100 arasında 10 tane sayi üretir
result_max=rnd_numbers.max()#üretilen sayilar içerisinden en buyugunu alir
result_min=rnd_numbers.min()#üretilen sayilar içerisinden en kucugunu alir
result_ort=rnd_numbers.mean()#üretilen sayilarin ort alir
result_max_index=rnd_numbers.argmax()#en buyuk sayinin indexi
result_min_index=rnd_numbers.argmin()#en kucuk sayinin indexi
print(rnd_numbers)
print(result_max)
print(result_max_index)
print(result_min)
print(result_min_index)
print(result_ort)

[94 31 35 70 73 74 96 45 91 66]
96
6
31
1
67.5
