In [5]:
import numpy as np

numbers=np.array([0,5,10,15,25,50,75])

result=numbers[5]
print(result)
result=numbers[-1]
print(result)
result=numbers[0:3]
print(result)
result=numbers[:3]
print(result)
result=numbers[::]
print(result)
result=numbers[::-1]
print(result)
result=numbers[::-2]
print(result)

50
75
[ 0  5 10]
[ 0  5 10]
[ 0  5 10 15 25 50 75]
[75 50 25 15 10  5  0]


In [15]:
numbers2=np.array([[0,5,10],[15,20,25],[50,75,85]])

result=numbers2[0]
print(result)
result=numbers2[2]
print(result)
result=numbers2[0,2]#0. satirın 2. indexindeki sayiyi almıs oluyoruz
print(result)
result=numbers2[2,1]#ikinci satirın 1. indexindeki sayiyi almıs oluyoruz
print(result)
result=numbers2[:,2]#tüm satirlardan 2. indextekileri almıs oluyoruz
print(result)
result=numbers2[:,0]#tüm satirların 0. indextekileri almıs oluyoruz
print(result)
result=numbers2[:,0:2]#tüm satirların 0. ve 1. indextekileri almıs oluyoruz
print(result)
result=numbers2[-1,:]#son satirları almıs oluyoruz
print(result)
result=numbers2[:3,:3]#tum satirları ve sutunlari almıs oluyoruz
print(result)
result=numbers2[:2,:2]#0 ve 1  satirin ve 0 ve 1. sutunlari almıs oluyoruz
print(result)

[ 0  5 10]
[50 75 85]
10
75
[10 25 85]
[ 0 15 50]
[[ 0  5]
 [15 20]
 [50 75]]
[50 75 85]
[[ 0  5 10]
 [15 20 25]
 [50 75 85]]
[[ 0  5]
 [15 20]]


In [17]:
arr1=np.arange(0,10)
arr2=arr1 #ayni adresi vermis oluyoruz
print(arr2)
print(arr1)
arr2[0]=20
print(arr2)
print(arr1)
#ikisinde de 0. indeksteki sayilar değişti çünkü bellek üzerinde aynı adreste tutulan aynı verileri listeliyoruz


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [19]:
arr1=np.arange(0,10)
arr2=arr1.copy() 
print(arr2)
print(arr1)
arr2[0]=20
print(arr2)
print(arr1)
#arr1 deki listeyi arr2 ye kopyaladık bu nedenle arr1 deki veri degismedi ikisinin de bellekteki yerleri farklidir


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]
