In [6]:
import numpy as np
num1=np.random.randint(10,100,6)
num2=np.random.randint(10,100,6)
print(num1)
print(num2)
result=num1+num2
print(result)
result=num1+10
print(result)
result=num1-num2
print(result)
result=num1-10
print(result)
result=num1*num2
print(result)
result=num1*10
print(result)
result=num1/num2
print(result)
result=num1/10
print(result)
result=num1+num2
print(result)
result=np.sin(num1)
print(result)
result=np.cos(num1)
print(result)
result=np.sqrt(num1)#karekök
print(result)
result=np.log(num1)#log
print(result)


[99 92 82 81 45 50]
[90 90 74 91 21 70]
[189 182 156 172  66 120]
[109 102  92  91  55  60]
[  9   2   8 -10  24 -20]
[89 82 72 71 35 40]
[8910 8280 6068 7371  945 3500]
[990 920 820 810 450 500]
[1.1        1.02222222 1.10810811 0.89010989 2.14285714 0.71428571]
[9.9 9.2 8.2 8.1 4.5 5. ]
[189 182 156 172  66 120]
[-0.99920683 -0.77946607  0.31322878 -0.62988799  0.85090352 -0.26237485]
[ 0.03982088 -0.62644445  0.9496777   0.77668598  0.52532199  0.96496603]
[9.94987437 9.59166305 9.05538514 9.         6.70820393 7.07106781]
[4.59511985 4.52178858 4.40671925 4.39444915 3.80666249 3.91202301]


In [10]:
mnum1=num1.reshape(2,3)#2x3 luk matrix yap
print(mnum1)
mnum2=num2.reshape(2,3)
print(mnum2)

result= np.vstack((mnum1,mnum2))#2x3 lük iki matrisi birlestirdi 4x3 e donustu
result= np.hstack((mnum1,mnum2))
#2x3 lük iki matrixren 2. matrixin 1. satirini alip, 1.matrixin 1. satirina ekledi.
#ayni islemi 2. matrisin 2. satiri için de yapti böylelikle yeni matrix 2x6 lık oldu
print(result)


[[99 92 82]
 [81 45 50]]
[[90 90 74]
 [91 21 70]]
[[99 92 82 90 90 74]
 [81 45 50 91 21 70]]


In [12]:
print(num1)
result =num1>=5#tüm elemanlari tek tek kontrol eder ve 5 ten buyuk olup olmadiğini yazdirir 
print(result)
result =num1%2==0 #tüm elemanlari tek tek kontrol eder ve çift olanlara True çevirir
print(result)

[99 92 82 81 45 50]
[ True  True  True  True  True  True]
[False  True  True False False  True]
