In [2]:
import numpy as np

In [5]:
result=np.array([10,15,30,45,60])
print(result)

[10 15 30 45 60]


In [7]:
#5-15 arasindaki sayilardan olusan numpy dizisi olustur
result=np.arange(5,15)
print(result)

[ 5  6  7  8  9 10 11 12 13 14]


In [8]:
#50-100 arasindaki sayilari +5 leyerek numpy dizisi olustur
result=np.arange(50,100,5)
print(result)

[50 55 60 65 70 75 80 85 90 95]


In [ ]:
# 10 tane sıfırdan olusan dizi
result=np.zeros(10)
print(result)

In [ ]:
# 10 birden sıfırdan olusan dizi
result=np.ones(10)
print(result)

In [9]:
#0-100 arasında esit aralıklı 5 sayi üret
result=np.linspace(0,100,5)
print(result)

[  0.  25.  50.  75. 100.]


In [10]:
#10-30 arasında rastgele 5 tam sayi üret
result=np.random.randint(10,30,5)
print(result)

[11 20 19 23 21]


In [11]:
#-1,1 arasında 10 sayı üret
result=np.random.randn(10)
print(result)

[ 1.96179795 -1.14899693 -0.96310912  1.01601653  1.72122009 -0.37998517
 -1.58654889 -0.19227122 -1.91994017 -0.52671892]


In [12]:
#(3x5) boyutlarinda 10-50 arasındaki sayilardan rastgele bir matris olustur
result=np.random.randint(10,50,15).reshape(3,5)
print(result)

[[20 10 44 47 39]
 [11 14 25 44 48]
 [26 42 42 33 17]]


In [16]:
#üretilen matrisin satir ve sutun sayılarının toplamini hesaplayiniz
result=np.random.randint(10,50,15).reshape(3,5)
rowTotal=result.sum(axis=1)
colTotal=result.sum(axis=0)
print(result)
print(rowTotal)
print(colTotal)

[[24 16 31 16 28]
 [49 10 40 20 45]
 [31 15 32 44 28]]
[115 164 150]
[104  41 103  80 101]


In [18]:
#uretilen matrixin en buyuk en kucuk ve ortalamasini bul
result=np.random.randint(10,50,15).reshape(3,5)
print(result)
result=result.max()
print(result)
result=result.min()
print(result)
result=result.mean()
print(result)

[[27 27 35 35 21]
 [28 18 47 31 35]
 [41 23 48 27 31]]
48
48
48.0


In [25]:
#en buyuk ve en kucuk degerinin indexi
result=np.random.randint(10,50,15).reshape(3,5)
print(result)
results=result.argmax()
print(results)
resulta=result.argmin()
print(resulta)

[[26 16 10 49 27]
 [30 42 44 26 18]
 [30 28 43 23 19]]
3
2


In [26]:
#10-20 arasındaki sayılari içeren dizinin ilk 3 elemanini seciniz
arr=np.arange(10,20)
print(arr)
result=arr[:3]
print(result)

[10 11 12 13 14 15 16 17 18 19]
[10 11 12]


In [27]:
#dizinin elemanlarini tersten yazdir
result=arr[::-1]
print(result)

[19 18 17 16 15 14 13 12 11 10]


In [28]:
#üretilen matrisin ilk satirini seciniz
result=np.random.randint(10,50,15).reshape(3,5)
result=result[0]
print(result)

[41 22 29 37 36]


In [29]:
#üretilen matrisin 2. satir 3. sutunundaki eleman?
result=np.random.randint(10,50,15).reshape(3,5)
result=result[1,2]
print(result)

43


In [30]:
#üretilen matrisin tüm satirlarindaki ilk eleman?
result=np.random.randint(10,50,15).reshape(3,5)
result=result[:,0]
print(result)

[45 40 25]


In [31]:
#üretilen matrisin her bir elemanının karesi?
result=np.random.randint(10,50,15).reshape(3,5)
result=result**2
print(result)

[[ 900 1521 1089 2116 1936]
 [ 361 1369 2025 2025 1681]
 [ 256  289 1600  841 1296]]


In [35]:
#üretilen matrisin hangisi çift pozitiftir
result=np.random.randint(-50,50,5)
ciftler=result[result%2==0]
result=ciftler[ciftler>0]
print(result)

[38]
