In [1]:
import pandas as pd
import numpy as np

In [4]:
data=np.random.randint(10,100,75).reshape(15,5)
print(data)

[[61 20 74 89 28]
 [69 87 35 58 66]
 [69 32 28 82 88]
 [63 70 70 28 90]
 [65 23 22 48 72]
 [91 41 56 26 43]
 [23 52 96 24 21]
 [45 54 18 18 83]
 [10 47 93 86 32]
 [95 39 27 56 61]
 [13 14 44 72 21]
 [68 77 50 99 84]
 [34 53 75 61 18]
 [40 70 31 95 33]
 [29 73 80 66 49]]


In [8]:
df=pd.DataFrame(data,columns=["column1","column2","column3","column4","column5"])
result=df
print(result)

    column1  column2  column3  column4  column5
0        91       24       71       42       44
1        57       16       93       47       62
2        44       75       10       52       32
3        47       58       18       21       26
4        54       21       91       43       91
5        97       60       85       27       89
6        49       68       43       54       94
7        44       59       64       56       75
8        62       25       16       78       22
9        61       28       61       60       85
10       65       90       71       95       84
11       59       80       47       73       79
12       13       82       77       23       35
13       62       97       24       67       23
14       83       26       69       27       34


In [10]:
result=df.columns
print(result)

Index(['column1', 'column2', 'column3', 'column4', 'column5'], dtype='object')


In [13]:
result=df.head(5)#baştan bes kayit
print(result)

   column1  column2  column3  column4  column5
0       91       24       71       42       44
1       57       16       93       47       62
2       44       75       10       52       32
3       47       58       18       21       26
4       54       21       91       43       91


In [14]:
result=df.head(10)
print(result)

   column1  column2  column3  column4  column5
0       91       24       71       42       44
1       57       16       93       47       62
2       44       75       10       52       32
3       47       58       18       21       26
4       54       21       91       43       91
5       97       60       85       27       89
6       49       68       43       54       94
7       44       59       64       56       75
8       62       25       16       78       22
9       61       28       61       60       85


In [15]:
result=df.tail(5)#sondan bes kayit
print(result)

    column1  column2  column3  column4  column5
10       65       90       71       95       84
11       59       80       47       73       79
12       13       82       77       23       35
13       62       97       24       67       23
14       83       26       69       27       34


In [19]:
result=df["column1"].head()#column1 in bastan 5 verisini getir
print(result)

0    91
1    57
2    44
3    47
4    54
Name: column1, dtype: int32


In [20]:
result=df.column1.head()#column1 in bastan 5 verisini getir
print(result)

0    91
1    57
2    44
3    47
4    54
Name: column1, dtype: int32


In [25]:
result=df[["column1","column2"]].head(5)#column1 ve column2 nin bastan 5 verisini getir
print(result)

   column1  column2
0       91       24
1       57       16
2       44       75
3       47       58
4       54       21


In [ ]:
result=df[["column1","column2"]].tail(5)#column1 in bastan 5 verisini getir
print(result)

In [33]:
result=df[5:15][["column1","column2"]].head()
print(result)

   column1  column2
5       97       60
6       49       68
7       44       59
8       62       25
9       61       28


In [32]:
result=df[5:15][["column1","column2"]].tail()
print(result)

    column1  column2
10       65       90
11       59       80
12       13       82
13       62       97
14       83       26


In [35]:
result=df>50
print(result)

    column1  column2  column3  column4  column5
0      True    False     True    False    False
1      True    False     True    False     True
2     False     True    False     True    False
3     False     True    False    False    False
4      True    False     True    False     True
5      True     True     True    False     True
6     False     True    False     True     True
7     False     True     True     True     True
8      True    False    False     True    False
9      True    False     True     True     True
10     True     True     True     True     True
11     True     True    False     True     True
12    False     True     True    False    False
13     True     True    False     True    False
14     True    False     True    False    False


In [36]:
result=df[df>50]
print(result)

    column1  column2  column3  column4  column5
0      91.0      NaN     71.0      NaN      NaN
1      57.0      NaN     93.0      NaN     62.0
2       NaN     75.0      NaN     52.0      NaN
3       NaN     58.0      NaN      NaN      NaN
4      54.0      NaN     91.0      NaN     91.0
5      97.0     60.0     85.0      NaN     89.0
6       NaN     68.0      NaN     54.0     94.0
7       NaN     59.0     64.0     56.0     75.0
8      62.0      NaN      NaN     78.0      NaN
9      61.0      NaN     61.0     60.0     85.0
10     65.0     90.0     71.0     95.0     84.0
11     59.0     80.0      NaN     73.0     79.0
12      NaN     82.0     77.0      NaN      NaN
13     62.0     97.0      NaN     67.0      NaN
14     83.0      NaN     69.0      NaN      NaN


In [37]:
result=df[df%2==0]
print(result)

    column1  column2  column3  column4  column5
0       NaN     24.0      NaN     42.0     44.0
1       NaN     16.0      NaN      NaN     62.0
2      44.0      NaN     10.0     52.0     32.0
3       NaN     58.0     18.0      NaN     26.0
4      54.0      NaN      NaN      NaN      NaN
5       NaN     60.0      NaN      NaN      NaN
6       NaN     68.0      NaN     54.0     94.0
7      44.0      NaN     64.0     56.0      NaN
8      62.0      NaN     16.0     78.0     22.0
9       NaN     28.0      NaN     60.0      NaN
10      NaN     90.0      NaN      NaN     84.0
11      NaN     80.0      NaN      NaN      NaN
12      NaN     82.0      NaN      NaN      NaN
13     62.0      NaN     24.0      NaN      NaN
14      NaN     26.0      NaN      NaN     34.0


In [43]:
result=df[df["column1"]>50][["column1"]]# column1 içerisinden 50 den buyuk gelen sayilari listele
print(result)

    column1
0        91
1        57
4        54
5        97
8        62
9        61
10       65
11       59
13       62
14       83


In [45]:
result=df[(df["column1"]>50) & (df["column1"]<70)][["column1"]]# column1 içerisinden 50 den buyuk ve 70 ten kücük gelen sayilari listele
print(result)

    column1
1        57
4        54
8        62
9        61
10       65
11       59
13       62


In [46]:
result=df[(df["column1"]>50) & (df["column2"]<70)][["column1","column2"]]
print(result)

    column1  column2
0        91       24
1        57       16
4        54       21
5        97       60
8        62       25
9        61       28
14       83       26


In [47]:
result=df[(df["column1"]>50) | (df["column2"]<70)][["column1","column2"]] #veya koşulu
print(result)

    column1  column2
0        91       24
1        57       16
3        47       58
4        54       21
5        97       60
6        49       68
7        44       59
8        62       25
9        61       28
10       65       90
11       59       80
13       62       97
14       83       26


In [48]:
result=df[(df["column1"]>50) | (df["column2"]>50)][["column1","column2"]] #veya koşulu
print(result)

    column1  column2
0        91       24
1        57       16
2        44       75
3        47       58
4        54       21
5        97       60
6        49       68
7        44       59
8        62       25
9        61       28
10       65       90
11       59       80
12       13       82
13       62       97
14       83       26


In [50]:
result=df.query("column1>=50&column1%2==0")
print(result)

    column1
4        54
8        62
13       62


In [ ]:
result=df.query("column1>=50&column1%2==0")[["column1"]]
print(result)

In [51]:
result=df.query("column1>=50|column1%2==0")[["column1"]]
print(result)

    column1
0        91
1        57
2        44
4        54
5        97
7        44
8        62
9        61
10       65
11       59
13       62
14       83
